export const posts = [
	{
		id: 1,
		image: 'accordion-slide1.jpg',
		author: 'Robin Jones',
		post_date: '18.03.2022',
		header: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Enim massa lectus tortor nunc, quisque mauris.  ',
	},
	{
		id: 2,
		image: 'accordion-slide2.jpg',
		author: 'Robin Jones 2',
		post_date: '18.03.2023',
		header: 'Lorem ipsum dolor sit amet',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestiae, maxime.',
	},
	{
		id: 3,
		image: 'accordion-slide3.jpg',
		author: 'Robin Jones 3',
		post_date: '18.03.2024',
		header: 'Lorem ipsum',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestiae, maxime.',
	},
	{
		id: 4,
		image: 'accordion-slide3.jpg',
		author: 'Robin Jones 4',
		post_date: '18.03.2024',
		header: 'Lorem ipsum',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestiae, maxime.',
	},
	{
		id: 5,
		image: 'accordion-slide3.jpg',
		author: 'Robin Jones 5',
		post_date: '18.03.2024',
		header: 'Lorem ipsum',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestiae, maxime.',
	},
]